CREATE TABLE MEMBER
(
    MEMBER_ID       INT UNSIGNED                                         NOT NULL AUTO_INCREMENT COMMENT '회원 아이디',
    EMAIL           VARCHAR(50)                                         NULL COMMENT '회원(사용자) 이메일',
    LOGIN_ID        VARCHAR(30)                                         NULL COMMENT '회원(기사, 관리자) 로그인 아이디',
    PASSWORD        VARCHAR(255)                                        NULL COMMENT '회원(기사, 관리자) 로그인 비밀번호',
    NAME            VARCHAR(25)                                         NULL COMMENT '회원(기사) 이름',
    PHONE_NUMBER    VARCHAR(20)                                         NULL COMMENT '회원(기사) 전화번호',
    ROLE            ENUM('NORMAL', 'DRIVER', 'ADMIN')                   NOT NULL COMMENT '권한(사용자, 기사, 관리자)',
    UNIQUE_KEY      VARCHAR(40)                                         NOT NULL COMMENT '회원 별 고유 아이디',
    APP_KEY         VARCHAR(60)                                         NULL COMMENT '모바일 기기 고유 아이디',
    VERIFIED_STATUS ENUM('CREATED', 'EMAIL_VERIFIED', 'FULLY_VERIFIED') NULL COMMENT '인증 상태(기사 회원 가입 절차)',
    LAST_LOGIN_AT   TIMESTAMP                                           NULL COMMENT '마지막 로그인 시간',
    CREATED_AT      TIMESTAMP                                           NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '계정 생성 시간',
    MODIFIED_AT     TIMESTAMP                                           NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '계정 수정 시간',
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UQ_MEMBER_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UQ_MEMBER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_UNIQUE_KEY UNIQUE (UNIQUE_KEY)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
COMMENT
'회원 테이블';


CREATE TABLE BUS
(
    BUS_ID           INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '버스 아이디',
    DRIVER_ID        INT UNSIGNED NOT NULL COMMENT '기사 아이디',
    BUS_ROUTE_ID     INT UNSIGNED NOT NULL COMMENT '버스 경로 아이디',
    BUS_NUMBER       varchar(10) NOT NULL COMMENT '버스 번호',
    OPERATION_STATUS boolean     NOT NULL DEFAULT FALSE COMMENT '버스 운행 상태',
    CREATED_AT       timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '버스 정보 생성 시간',
    MODIFIED_AT      timestamp   NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '버스 정보 수정 시간',
    CONSTRAINT PK_BUS PRIMARY KEY (BUS_ID),
    CONSTRAINT UQ_BUS_NUMBER UNIQUE (BUS_NUMBER),
    INDEX            IX_BUS_DRIVER_ID(DRIVER_ID),
    INDEX            IX_BUS_ROUTE_ID(BUS_ROUTE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
COMMENT
'버스 테이블';

CREATE TABLE BUS_LOCATION_LOG
(
    LOCATION_ID BINARY (16) NOT NULL COMMENT '버스 위치 정보 로그 아이디',
    BUS_ID       INT UNSIGNED                       NOT NULL COMMENT '버스 아이디',
    OPERATION_ID INT UNSIGNED                       NOT NULL COMMENT '버스 운행 정보 아이디',
    LONGITUDE    DOUBLE                            NOT NULL COMMENT '버스 위치 경도 값',
    LATITUDE     DOUBLE                            NOT NULL COMMENT '버스 위치 위도 값',
    STATUS       ENUM('DRIVE', 'STOP', 'ACCIDENT') NOT NULL DEFAULT 'DRIVE' COMMENT '버스 현재 상태',
    CREATED_AT   TIMESTAMP                         NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '버스 위치 시간',
    CONSTRAINT PK_BUS_LOCATION_LOG PRIMARY KEY (LOCATION_ID),
    INDEX        IX_BUS_LOCATION_LOG_BUS_ID(BUS_ID),
    INDEX        IX_BUS_LOCATION_LOG_OPERATION_ID(OPERATION_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
COMMENT
'버스 위치 로그 테이블';

CREATE TABLE BUS_OPERATION
(
    OPERATION_ID         INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '버스 운행 정보 아이디',
    DRIVER_ID            INT UNSIGNED NOT NULL COMMENT '버스 기사 아이디',
    BUS_ID               INT UNSIGNED NOT NULL COMMENT '버스 아이디',
    OPERATION_START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '버스 운행 시작 시간',
    OPERATION_END_TIME   TIMESTAMP DEFAULT NULL COMMENT '버스 운행 종료 시간',
    CONSTRAINT PK_BUS_OPERATION PRIMARY KEY (OPERATION_ID),
    INDEX                IX_BUS_OPERATION_DRIVER_ID(DRIVER_ID),
    INDEX                IX_BUS_OPERATION_BUS_ID(BUS_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
COMMENT
'버스 운행 정보 테이블';

CREATE TABLE BUS_ROUTE
(
    ROUTE_ID    INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '버스 노선 아이디',
    ROUTE_NAME  VARCHAR(60) NOT NULL COMMENT '노선 이름',
    CREATED_AT  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '버스 노선 생성 시간',
    MODIFIED_AT TIMESTAMP   NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '버스 노선 수정 시간',
    CONSTRAINT PK_BUS_ROUTE PRIMARY KEY (ROUTE_ID),
    CONSTRAINT UQ_BUS_ROUTE_NAME UNIQUE (ROUTE_NAME)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
COMMENT
'버스 노선 테이블';

CREATE TABLE BUS_STATION
(
    STATION_ID   INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '버스 정류장 아이디',
    STATION_NAME VARCHAR(60)  NOT NULL COMMENT '버스 정류장 이름',
    DESCRIPTION  VARCHAR(200) NULL     DEFAULT NULL COMMENT '버스 정류장 상세 설명(EX: 상세 위치)',
    LONGITUDE    DOUBLE       NOT NULL COMMENT '버스 정류장 경도 값',
    LATITUDE     DOUBLE       NOT NULL COMMENT '버스 정류장 위도 값',
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '버스 정류장 생성 시간',
    MODIFIED_AT  TIMESTAMP    NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '버스 정류장 수정 시간',
    CONSTRAINT PK_BUS_STATION PRIMARY KEY (STATION_ID),
    CONSTRAINT UQ_BUS_STATION_NAME UNIQUE (STATION_NAME)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
COMMENT
'버스 정류장 테이블';

CREATE TABLE BUS_ROUTE_STATION
(
    BUS_ROUTE_STATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '버스 노선 - 정류장 아이디',
    BUS_ROUTE_ID         INT UNSIGNED NOT NULL COMMENT '버스 노선 아이디',
    BUS_STATION_ID       INT UNSIGNED NOT NULL COMMENT '버스 정류장 아이디',
    CONSTRAINT PK_BUS_ROUTE_STATION PRIMARY KEY (BUS_ROUTE_STATION_ID),
    INDEX                IX_BUS_ROUTE_STATION_ROUTE_ID(BUS_ROUTE_ID),
    INDEX                IX_BUS_ROUTE_STATION_STATION_ID(BUS_STATION_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
COMMENT
'버스 노선 - 버스 정류장 중간 테이블';


CREATE TABLE NOTIFICATION
(
    NOTIFICATION_ID INT UNSIGNED                              NOT NULL AUTO_INCREMENT COMMENT '알림 아이디',
    SENDER_ID       INT UNSIGNED                              NOT NULL COMMENT '알링 송신자 아이디',
    RECEIVER_ID     INT UNSIGNED                              NOT NULL COMMENT '알림 수신자 아이디',
    TITLE           VARCHAR(50)                              NOT NULL COMMENT '알림 제목',
    CONTENT         VARCHAR(500)                             NULL COMMENT '알림 내용',
    TYPE            ENUM('GENERAL', 'IMPORTANT', 'CRITICAL') NOT NULL COMMENT '알림 종류',
    CREATED_AT      TIMESTAMP                                NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '알림 생성 시간',
    CONSTRAINT PK_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID),
    INDEX           IDX_NOTIFICATION_SENDER_BY(SENDER_ID ASC),
    INDEX           IDX_NOTIFICATION_RECEIVER_BY(RECEIVER_ID ASC),
    INDEX           IDX_NOTIFICATION_CREATED_DESC_BY(CREATED_AT DESC)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
COMMENT
'알림 테이블';

CREATE TABLE MEMBER_ROUTE_LIKE
(
    MEMBER_ROUTE_LIKE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '사용자 버스 노선 좋아요 아이디',
    LIKE_MEMBER_ID       INT UNSIGNED NOT NULL COMMENT '좋아요 누른 회원 아이디',
    BUS_ROUTE_ID         INT UNSIGNED NOT NULL COMMENT '좋아요 누른 버스 노선 아이디',
    CREATED_AT           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '좋아요 누른 시간',
    CONSTRAINT PK_MEMBER_ROUTE_LIKE PRIMARY KEY (MEMBER_ROUTE_LIKE_ID),
    INDEX                IDX_LIKE_BY_ROUTE(BUS_ROUTE_ID, LIKE_MEMBER_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
COMMENT
'회원 노선 좋아요 테이블'
